server:
  port: 8686                 #https端口
  http:
    port: 8086              #http端口
  ssl:
    key-store: classpath:chengdashi.cn.jks
    key-store-password: q94gwoelbq5zeug              #压缩包解压里面会有
    key-store-type: JKS
    enabled: true
wx:
  miniapp:
    configs:
      - appid: wx2b1b9f396a67b94c  #微信小程序的appid
        secret: b76856231c6db17c47e3e88779c95889 #微信小程序的Secret
        token: bigdatastudio666 #微信小程序消息服务器配置的token
        aesKey: 38iWpSLrffHLNdw1740GiZlYFIIZL5Kjd1hYSvmfhtF #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
