server:
    port: 8888
wx:
  miniapp:
    configs:
      - appid: wx2b1b9f396a67b94c
        secret: b76856231c6db17c47e3e88779c95889
        token: #微信小程序消息服务器配置的token
        aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON
