server:
  port: 8888
spring:
  datasource:
    username: root               #数据库的用户名
    password: mysql729           #数据库的密码
    url: jdbc:mysql://localhost:3306/nyc?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8   #url
    driver-class-name: com.mysql.cj.jdbc.Driver             #数据库的驱动
mybatis-plus:
  configuration:
    call-setters-on-nulls: true                             #如果map查出字段为空，也显示
    #org.apache.ibatis.logging.stdout.StdOutImpl 控制台打印sql语句方便调试sql语句执行错误
    #org.apache.ibatis.logging.log4j2.Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true                          #下划线转驼峰
    cache-enabled: true                           # 开启二级缓存
  mapper-locations: classpath*:**/xml/*.xml
  type-aliases-package: com.example.domain
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1
      id-type: assign_id



