server:
  port: 8888
## 配置jasypt相关信息
#jasypt:
#  encryptor:
#    password: PEB123@321BEP
#    # 配置加密算法
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator
#    property:
#      # 算法识别前缀(当算法发现配置文件中的值以这前缀开始，后缀结尾时，会使用指定算法解密)
#      prefix: IT(
#      # 算法识别后缀
#      suffix: )

# 指定bean
jasypt:
  encryptor:
    bean: CodeEncryBean
    property:
      prefix: DONG(
      suffix: )

